<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Carbon;

class watermark extends Controller
{
    public function ard(Request $request){

        $options = new Options();
        $options->set("isHtml5ParserEnabled", true);
        $options->set("isPhpEnabled", true); 
        
        $dompdf = new Dompdf($options);

        $html = '<!DOCTYPE html>';
        $html .= '<html>';
        $html .= '<head>';
        $html .= '<title>water mark</title>';
        $html .= '<style>';
        $html .= '    body { font-family: "bi", sans-serif; line-height: 1.6; margin: 0; padding: 0; background-size: cover; background-position: center; background-repeat: no-repeat; }';
        $html .= '    footer { text-align: center; padding: 0px; width: 100%; }';
        $html .= '</style>';
        $html .= '</head>';
        $html .= '<body>';


        $html .= '</body>';
        $html .= '</html>';

        // echo $html;

        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4');
        $dompdf->render();

        $canvas = $dompdf->getCanvas();
        $imageBase64 = base64_encode(file_get_contents(public_path('uploads/X.png')));
        $imageMimeType = 'image/png';
        $imageWidth = 500;
        $imageHeight = 500;
        $watermarkText = "GENERATED BY DOMPDF WATERMARK SYSTEM";

        $fontMetrics = $dompdf->getFontMetrics();

        $canvas->page_script(function ($pageNumber, $pageCount, $canvas) use ($fontMetrics, $imageBase64, $imageMimeType, $imageWidth, $imageHeight, $watermarkText) {
            $pageWidth = $canvas->get_width();
            $pageHeight = $canvas->get_height();

            $imageX = ($pageWidth - $imageWidth) / 2;
            $imageY = ($pageHeight - $imageHeight) / 2;

            $canvas->set_opacity(0.2);
            $canvas->image('data:' . $imageMimeType . ';base64,' . $imageBase64, $imageX, $imageY, $imageWidth, $imageHeight, 'png');

            $canvas->set_opacity(1);

            $font = $fontMetrics->getFont("Times-Roman");
            $fontSize = 9;
            $textWidth = $fontMetrics->getTextWidth($watermarkText, $font, $fontSize);
            $textX = 20;
            $textY = $pageHeight -200; 

            $canvas->page_text($textX, $textY, $watermarkText, $font, $fontSize, [0.5, 0.5, 0.5], 0.0, 3, -90);
            // $textX: X-coordinate (horizontal position) of the text, measured in points from the left edge of the page.
            // $textY: Y-coordinate (vertical position) of the text, measured in points from the top edge of the page.
            // $watermarkText: The text to be displayed as the watermark.
            // $font: The font used for the text. Must be a valid font recognized by Dompdf.
            // $fontSize: The size of the font in points.
            // [0.5, 0.5, 0.5]: RGB color values for the text. [0.5, 0.5, 0.5] represents a medium gray color.
            // 0.0: Word spacing. A value of 0.0 applies default spacing between words.
            // 3: Character spacing. A value of 3 adds spacing between each character in the text.
            // -90: Rotation angle in degrees. -90 rotates the text counterclockwise to appear vertically aligned.
            $canvas->set_opacity(1);
        });
        
        $dompdf->stream('Attendance report.pdf', ['Attachment' => false]);
    }
}
